/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Pete
 */
public class Calculator extends javax.swing.JFrame implements ActionListener{

	//My variables for action listener
	StringBuilder currentNum = new StringBuilder();
	double total = 0;
	double lastNum = 0;
	String operator = "";
	//-------------------------------------

	/**
	 * Creates new form Calculator
	 */
	public Calculator() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jButton18 = new javax.swing.JButton();
		jButton19 = new javax.swing.JButton();
		jButton20 = new javax.swing.JButton();
		jButton21 = new javax.swing.JButton();
		jButton22 = new javax.swing.JButton();
		jButton23 = new javax.swing.JButton();
		jButton24 = new javax.swing.JButton();
		jButton25 = new javax.swing.JButton();
		jButton26 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jButton2.setIcon(new javax.swing.ImageIcon("back.png"));
		jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton2.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton2.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton2.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton2.addActionListener(this);

		jButton5.setText("C");
		jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton5.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton5.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton5.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton5.addActionListener(this);

		jButton6.setText("CE");
		jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jButton6.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton6.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton6.addActionListener(this);

		jButton7.setIcon(new javax.swing.ImageIcon("plusminus.png"));
		jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton7.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton7.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton7.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton7.addActionListener(this);

		jButton8.setText("7");
		jButton8.setToolTipText("");
		jButton8.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton8.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton8.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton8.addActionListener(this);

		jButton9.setIcon(new javax.swing.ImageIcon("sqrt.png"));
		jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton9.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton9.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton9.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton9.addActionListener(this);

		jButton10.setText("9");
		jButton10.setToolTipText("");
		jButton10.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton10.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton10.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton10.addActionListener(this);

		jButton11.setText("8");
		jButton11.setToolTipText("");
		jButton11.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton11.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton11.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton11.addActionListener(this);

		jButton12.setText("/");
		jButton12.setToolTipText("");
		jButton12.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton12.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton12.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton12.addActionListener(this);

		jButton13.setText("%");
		jButton13.setToolTipText("");
		jButton13.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton13.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton13.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton13.addActionListener(this);

		jButton14.setText("5");
		jButton14.setToolTipText("");
		jButton14.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton14.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton14.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton14.addActionListener(this);

		jButton15.setText("4");
		jButton15.setToolTipText("");
		jButton15.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton15.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton15.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton15.addActionListener(this);

		jButton16.setText("6");
		jButton16.setToolTipText("");
		jButton16.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton16.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton16.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton16.addActionListener(this);

		jButton17.setText("*");
		jButton17.setToolTipText("");
		jButton17.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton17.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton17.setPreferredSize(new java.awt.Dimension(32, 28));
		jButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		this.jButton17.addActionListener(this);

		jButton18.setText("1/x");
		jButton18.setToolTipText("");
		jButton18.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton18.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton18.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton18.addActionListener(this);

		jButton19.setText("1");
		jButton19.setToolTipText("");
		jButton19.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton19.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton19.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton19.addActionListener(this);

		jButton20.setText("2");
		jButton20.setToolTipText("");
		jButton20.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton20.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton20.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton20.addActionListener(this);

		jButton21.setText("3");
		jButton21.setToolTipText("");
		jButton21.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton21.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton21.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton21.addActionListener(this);

		jButton22.setText("-");
		jButton22.setToolTipText("");
		jButton22.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton22.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton22.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton22.addActionListener(this);

		jButton23.setText("0");
		jButton23.setToolTipText("");
		jButton23.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton23.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton23.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton23.addActionListener(this);

		jButton24.setText(".");
		jButton24.setToolTipText("");
		jButton24.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton24.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton24.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton24.addActionListener(this);

		jButton25.setText("+");
		jButton25.setToolTipText("");
		jButton25.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton25.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton25.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton25.addActionListener(this);

		jButton26.setText("=");
		jButton26.setToolTipText("");
		jButton26.setMargin(new java.awt.Insets(2, 4, 2, 4));
		jButton26.setMaximumSize(new java.awt.Dimension(39, 23));
		jButton26.setPreferredSize(new java.awt.Dimension(32, 28));
		this.jButton26.addActionListener(this);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE))
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(10, 10, 10)
																		.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(jPanel2Layout.createSequentialGroup()
																						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
																										.addGroup(jPanel2Layout.createSequentialGroup()
																												.addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
																												.addGroup(jPanel2Layout.createSequentialGroup()
																														.addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																														.addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
																														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																														.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																.addGroup(jPanel2Layout.createSequentialGroup()
																																		.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
																																		.addGroup(jPanel2Layout.createSequentialGroup()
																																				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																																						.addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																																						.addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
																																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																																								.addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																																								.addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
																																								.addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
																																								.addContainerGap())
				);

		jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton11, jButton12, jButton13, jButton14, jButton15, jButton2, jButton5, jButton6, jButton7, jButton8, jButton9});

		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																		.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																				.addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																								.addGroup(jPanel2Layout.createSequentialGroup()
																										.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																												.addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																												.addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																												.addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																														.addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																														.addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
																														.addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																														.addContainerGap())
				);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(25, 25, 25))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(38, 38, 38))
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents


	//---------------------------------------------------------Beginning of my main Code(Jonathan Kosir)
	/**
	 * The Part I did made action listeners
	 * Jonathan Kosir
	 * Project 6
	 */
	public void actionPerformed(ActionEvent e) {

		//Does the adding by calling a method
		if(e.getSource() == jButton25)
		{
			operationRead("ADD");

		}

		//Add decimal to string to be shown and stored
		if(e.getSource() == jButton24)
		{
			if(!(currentNum.toString().contains(".")))
			{
				currentNum.append(".");
			}
		}

		//Adds zero to display and current num and displays new value
		if(e.getSource() == jButton23)
		{
			currentNum.append(0);
			jTextField1.setText(currentNum.toString());
		}

		//Does the subtracting by calling a method
		if(e.getSource() == jButton22)
		{
			operationRead("SUB");
		}

		//Adds 3 to display and current num and displays new value
		if(e.getSource() == jButton21)
		{
			currentNum.append(3);
			jTextField1.setText(currentNum.toString());
		}

		//Adds 2 to display and current num and displays new value
		if(e.getSource() == jButton20)
		{
			currentNum.append(2);
			jTextField1.setText(currentNum.toString());
		}

		//Adds 1 to display and current num and displays new value
		if(e.getSource() == jButton19)
		{
			currentNum.append(1);
			jTextField1.setText(currentNum.toString());
		}

		//Does the reciprocal stores the value and displays it
		if(e.getSource() == jButton18)
		{
			try
			{
				total = 1/Double.parseDouble(jTextField1.getText());
				currentNum.delete(0, currentNum.length());
				currentNum.append(total);
				jTextField1.setText(currentNum.toString());
			}
			catch(Exception ex)
			{
				ex.getMessage();
			}
		}

		//Does the multiplying by calling a method
		if(e.getSource() == jButton17)
		{
			operationRead("MUL");
		}

		//Adds 6 to display and current num and displays new value
		if(e.getSource() == jButton16)
		{
			currentNum.append(6);	
			jTextField1.setText(currentNum.toString());
		}

		//Adds 4 to display and current num and displays new value
		if(e.getSource() == jButton15)
		{
			currentNum.append(4);
			jTextField1.setText(currentNum.toString());
		}

		//Adds 5 to display and current num and displays new value
		if(e.getSource() == jButton14)
		{
			currentNum.append(5);
			jTextField1.setText(currentNum.toString());
		}

		//The % action listener does nothing
		if(e.getSource() == jButton13)
		{

		}

		//Does the deviding by calling a method
		if(e.getSource() == jButton12)
		{
			operationRead("DEV");
		}

		//Adds 8 to display and current num and displays new value
		if(e.getSource() == jButton11)
		{
			currentNum.append(8);
			jTextField1.setText(currentNum.toString());
		}

		//Adds 9 to display and current num and displays new value
		if(e.getSource() == jButton10)
		{
			currentNum.append(9);	
			jTextField1.setText(currentNum.toString());
		}

		//Does the square root stores the value and displays it
		if(e.getSource() == jButton9)
		{
			try
			{
				total = Math.sqrt(Double.parseDouble(jTextField1.getText()));
				currentNum.delete(0, currentNum.length());
				currentNum.append(total);
				jTextField1.setText(currentNum.toString());
			}
			catch(Exception ex)
			{
				ex.getMessage();
			}
		}

		//Adds 7 to display and current num and displays new value
		if(e.getSource() == jButton8)
		{
			currentNum.append(7);	
			jTextField1.setText(currentNum.toString());
		}

		//Does the oppisite sign of displayed stores the value and displays it
		if(e.getSource() == jButton7)
		{
			if(Double.parseDouble(jTextField1.getText())!=0)
			{
				total = -(Double.parseDouble(jTextField1.getText()));
				currentNum.delete(0, currentNum.length());
				currentNum.append(total); 
				jTextField1.setText(currentNum.toString());
			}
		}

		//Clears whats currently displayed
		if(e.getSource() == jButton6)
		{
			currentNum.delete(0, currentNum.length());
			jTextField1.setText(currentNum.toString());
		}

		//clears all
		if(e.getSource() == jButton5)
		{
			total = 0;
			lastNum = 0;
			currentNum.delete(0, currentNum.length());
			jTextField1.setText(currentNum.toString());
			operator = "";
		}

		//Backspaces on value from the right
		if(e.getSource() == jButton2)
		{
			currentNum.delete(currentNum.length()-1, currentNum.length());
			jTextField1.setText(currentNum.toString());
		}

		//Does the process when equals is pressed calls a method to do current
		//operation stores value and displays it
		if(e.getSource() == jButton26)
		{
			double result = 0;
			try
			{
				result = processOperation();
				currentNum.delete(0, currentNum.length());
				currentNum.append(result);
				lastNum = result;
				jTextField1.setText(currentNum.toString());
			}
			catch(Exception ex)
			{
				ex.getMessage();
			}
			operator = "";
		}
	}  

	/**
	 * Does all the operations when called and stores the total
	 * @return the total after operation is done
	 */
	public double processOperation()
	{
		switch(operator){
		case "ADD":	
			total = lastNum + Double.parseDouble(jTextField1.getText());
			break;
		case "SUB":	
			total = lastNum - Double.parseDouble(jTextField1.getText());
			break;
		case "MUL":	
			total = lastNum * Double.parseDouble(jTextField1.getText());
			break;
		case "DEV":	
			try
			{
				total = lastNum / Double.parseDouble(jTextField1.getText());
			}
			catch(Exception ex)
			{
				ex.getMessage();
			}
			break;
		}
		return total;
	}

	/**
	 * Is called when a opperation is pressed checkes what that operation is
	 * by reading into the param then changes the global operation variable
	 * stores total previous num and set current num to 0
	 * @param op the operation to be done
	 */
	public void operationRead(String op)
	{
		double numInField =  Double.parseDouble(jTextField1.getText());
		if(!operator.equals(""))
		{
			try
			{
				total = processOperation();
				lastNum = total;
				currentNum.delete(0, currentNum.length());
				currentNum.append(total);
				jTextField1.setText(currentNum.toString());
			}
			catch(Exception ex)
			{
				ex.getMessage();
			}
		}
		else
		{
			lastNum = numInField;
		}
		currentNum.delete(0, currentNum.length());
		operator = op;
	}
	//-------------------------------------------------------------- End Of My Code (Jonathan Kosir)


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		Calculator calc = new Calculator();
		calc.setVisible(true);
	}
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton23;
	private javax.swing.JButton jButton24;
	private javax.swing.JButton jButton25;
	private javax.swing.JButton jButton26;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}